version: "3.8"
services:

  telegram-bot:
    build: ./src/telegram_bot
    container_name: telegram_bot
    restart: unless-stopped
    networks:
      - genesis-network

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    ports:
      - 8000:8000
    networks:
      - genesis-network
  
  ml:
    build: ./src/ml
    container_name: ml
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - genesis-network

volumes:
  index_data:


networks:
  genesis-network:
    driver: bridge
