version: "3.8"
services:

  telegram-bot:
    build: ./src/telegram_bot
    container_name: telegram_bot
    restart: unless-stopped
    networks:
      - genesis-network

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - genesis-network

volumes:
  index_data:


networks:
  genesis-network:
    driver: bridge
